# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8866d2724b77245eaa4c8b420b25eee5fe7a99f3bd4a726659a828fde5befeaf47ecd8142a648a951fd1dd6f250b839ca5659fd26da407f39836bbffe9541f6

test:
  secret_key_base: 70247562f8f0150fd37c45fbb661726ba777e04ceee3478edbea8589d307ebfae3ae2f51998a7048be399a650328be617da10a0c13b460313800e7468a282e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
